export const contractADDR = '0x133818926101eEE247B1188fcE4a13f993d9c6E8';

export const contractABI =  [
        {
           "anonymous":false,
           "inputs":[
              {
                 "indexed":false,
                 "internalType":"address",
                 "name":"admin",
                 "type":"address"
              }
           ],
           "name":"AddAdmin",
           "type":"event"
        },
        {
           "anonymous":false,
           "inputs":[
              {
                 "indexed":false,
                 "internalType":"address",
                 "name":"campaignAddress",
                 "type":"address"
              },
              {
                 "indexed":false,
                 "internalType":"uint256",
                 "name":"campaign_id",
                 "type":"uint256"
              }
           ],
           "name":"CampaignCancelled",
           "type":"event"
        },
        {
           "anonymous":false,
           "inputs":[
              {
                 "indexed":false,
                 "internalType":"address",
                 "name":"campaignAddress",
                 "type":"address"
              },
              {
                 "indexed":false,
                 "internalType":"uint256",
                 "name":"campaign_id",
                 "type":"uint256"
              }
           ],
           "name":"CampaignCompleted",
           "type":"event"
        },
        {
           "anonymous":false,
           "inputs":[
              {
                 "indexed":false,
                 "internalType":"uint256",
                 "name":"campaign_id",
                 "type":"uint256"
              },
              {
                 "indexed":false,
                 "internalType":"address",
                 "name":"campaignAddress",
                 "type":"address"
              },
              {
                 "indexed":false,
                 "internalType":"string",
                 "name":"title",
                 "type":"string"
              },
              {
                 "indexed":false,
                 "internalType":"uint256",
                 "name":"targetAmount",
                 "type":"uint256"
              },
              {
                 "indexed":false,
                 "internalType":"uint256",
                 "name":"deadline",
                 "type":"uint256"
              }
           ],
           "name":"CampaignCreated",
           "type":"event"
        },
        {
           "anonymous":false,
           "inputs":[
              {
                 "indexed":false,
                 "internalType":"address",
                 "name":"donor",
                 "type":"address"
              },
              {
                 "indexed":false,
                 "internalType":"uint256",
                 "name":"amount",
                 "type":"uint256"
              },
              {
                 "indexed":false,
                 "internalType":"address",
                 "name":"campaignAddress",
                 "type":"address"
              },
              {
                 "indexed":false,
                 "internalType":"uint256",
                 "name":"campaign_id",
                 "type":"uint256"
              }
           ],
           "name":"DonationReceived",
           "type":"event"
        },
        {
           "anonymous":false,
           "inputs":[
              {
                 "indexed":false,
                 "internalType":"uint256",
                 "name":"amount",
                 "type":"uint256"
              },
              {
                 "indexed":false,
                 "internalType":"address",
                 "name":"by",
                 "type":"address"
              },
              {
                 "indexed":false,
                 "internalType":"address",
                 "name":"to",
                 "type":"address"
              },
              {
                 "indexed":false,
                 "internalType":"address",
                 "name":"from",
                 "type":"address"
              },
              {
                 "indexed":false,
                 "internalType":"uint256",
                 "name":"campaignId",
                 "type":"uint256"
              }
           ],
           "name":"FundsWithdrawn",
           "type":"event"
        },
        {
           "anonymous":false,
           "inputs":[
              {
                 "indexed":false,
                 "internalType":"address",
                 "name":"campaignAddress",
                 "type":"address"
              },
              {
                 "indexed":false,
                 "internalType":"uint256",
                 "name":"campaignId",
                 "type":"uint256"
              },
              {
                 "indexed":false,
                 "internalType":"address",
                 "name":"to",
                 "type":"address"
              },
              {
                 "indexed":false,
                 "internalType":"uint256",
                 "name":"amount",
                 "type":"uint256"
              }
           ],
           "name":"RefundCampaignDonors",
           "type":"event"
        },
        {
           "anonymous":false,
           "inputs":[
              {
                 "indexed":false,
                 "internalType":"address",
                 "name":"admin",
                 "type":"address"
              }
           ],
           "name":"RemoveAdmin",
           "type":"event"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"_admin",
                 "type":"address"
              }
           ],
           "name":"addCampaignAdmin",
           "outputs":[
              
           ],
           "stateMutability":"nonpayable",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"",
                 "type":"address"
              },
              {
                 "internalType":"address",
                 "name":"",
                 "type":"address"
              }
           ],
           "name":"admins",
           "outputs":[
              {
                 "internalType":"bool",
                 "name":"",
                 "type":"bool"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"",
                 "type":"address"
              },
              {
                 "internalType":"uint256",
                 "name":"",
                 "type":"uint256"
              }
           ],
           "name":"campaignAdmins",
           "outputs":[
              {
                 "internalType":"address",
                 "name":"",
                 "type":"address"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"",
                 "type":"address"
              },
              {
                 "internalType":"uint256",
                 "name":"",
                 "type":"uint256"
              }
           ],
           "name":"campaigns",
           "outputs":[
              {
                 "internalType":"uint256",
                 "name":"campaign_id",
                 "type":"uint256"
              },
              {
                 "internalType":"string",
                 "name":"title",
                 "type":"string"
              },
              {
                 "internalType":"string",
                 "name":"description",
                 "type":"string"
              },
              {
                 "internalType":"address",
                 "name":"campaignAddress",
                 "type":"address"
              },
              {
                 "internalType":"uint256",
                 "name":"targetAmount",
                 "type":"uint256"
              },
              {
                 "internalType":"uint256",
                 "name":"raisedAmount",
                 "type":"uint256"
              },
              {
                 "internalType":"uint256",
                 "name":"balance",
                 "type":"uint256"
              },
              {
                 "internalType":"uint256",
                 "name":"deadline",
                 "type":"uint256"
              },
              {
                 "internalType":"bool",
                 "name":"isCompleted",
                 "type":"bool"
              },
              {
                 "internalType":"bool",
                 "name":"isCancelled",
                 "type":"bool"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"uint256",
                 "name":"_campaignId",
                 "type":"uint256"
              },
              {
                 "internalType":"address",
                 "name":"_campaignAddress",
                 "type":"address"
              }
           ],
           "name":"cancelCampaign",
           "outputs":[
              
           ],
           "stateMutability":"nonpayable",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"string",
                 "name":"_title",
                 "type":"string"
              },
              {
                 "internalType":"string",
                 "name":"_description",
                 "type":"string"
              },
              {
                 "internalType":"uint256",
                 "name":"_target",
                 "type":"uint256"
              },
              {
                 "internalType":"uint256",
                 "name":"_durationdays",
                 "type":"uint256"
              }
           ],
           "name":"createCampaign",
           "outputs":[
              
           ],
           "stateMutability":"nonpayable",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address payable",
                 "name":"_campaignAddress",
                 "type":"address"
              },
              {
                 "internalType":"uint256",
                 "name":"_campaignId",
                 "type":"uint256"
              },
              {
                 "internalType":"uint256",
                 "name":"_amount",
                 "type":"uint256"
              }
           ],
           "name":"donateToCampaign",
           "outputs":[
              
           ],
           "stateMutability":"payable",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"",
                 "type":"address"
              },
              {
                 "internalType":"uint256",
                 "name":"",
                 "type":"uint256"
              }
           ],
           "name":"donors",
           "outputs":[
              {
                 "internalType":"address",
                 "name":"campaignAddress",
                 "type":"address"
              },
              {
                 "internalType":"uint256",
                 "name":"campaignId",
                 "type":"uint256"
              },
              {
                 "internalType":"string",
                 "name":"title",
                 "type":"string"
              },
              {
                 "internalType":"uint256",
                 "name":"amount",
                 "type":"uint256"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"",
                 "type":"address"
              },
              {
                 "internalType":"uint256",
                 "name":"",
                 "type":"uint256"
              },
              {
                 "internalType":"uint256",
                 "name":"",
                 "type":"uint256"
              }
           ],
           "name":"donorsForCampaign",
           "outputs":[
              {
                 "internalType":"address",
                 "name":"by",
                 "type":"address"
              },
              {
                 "internalType":"uint256",
                 "name":"amount",
                 "type":"uint256"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"uint256",
                 "name":"_campaignId",
                 "type":"uint256"
              },
              {
                 "internalType":"address",
                 "name":"_campaignAddress",
                 "type":"address"
              }
           ],
           "name":"getCampaignDetails",
           "outputs":[
              {
                 "components":[
                    {
                       "internalType":"uint256",
                       "name":"campaign_id",
                       "type":"uint256"
                    },
                    {
                       "internalType":"string",
                       "name":"title",
                       "type":"string"
                    },
                    {
                       "internalType":"string",
                       "name":"description",
                       "type":"string"
                    },
                    {
                       "internalType":"address",
                       "name":"campaignAddress",
                       "type":"address"
                    },
                    {
                       "internalType":"uint256",
                       "name":"targetAmount",
                       "type":"uint256"
                    },
                    {
                       "internalType":"uint256",
                       "name":"raisedAmount",
                       "type":"uint256"
                    },
                    {
                       "internalType":"uint256",
                       "name":"balance",
                       "type":"uint256"
                    },
                    {
                       "internalType":"uint256",
                       "name":"deadline",
                       "type":"uint256"
                    },
                    {
                       "internalType":"bool",
                       "name":"isCompleted",
                       "type":"bool"
                    },
                    {
                       "internalType":"bool",
                       "name":"isCancelled",
                       "type":"bool"
                    }
                 ],
                 "internalType":"struct CharityDonationStorage.Campaign",
                 "name":"campaign",
                 "type":"tuple"
              },
              {
                 "internalType":"uint256",
                 "name":"donorsNumber",
                 "type":"uint256"
              },
              {
                 "components":[
                    {
                       "internalType":"address",
                       "name":"by",
                       "type":"address"
                    },
                    {
                       "internalType":"uint256",
                       "name":"amount",
                       "type":"uint256"
                    }
                 ],
                 "internalType":"struct CharityDonationStorage.CampaignDonors[]",
                 "name":"campaigndonors",
                 "type":"tuple[]"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"uint256",
                 "name":"_campaignId",
                 "type":"uint256"
              },
              {
                 "internalType":"address",
                 "name":"_campaignAddress",
                 "type":"address"
              }
           ],
           "name":"refundDonors",
           "outputs":[
              
           ],
           "stateMutability":"nonpayable",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"_admin",
                 "type":"address"
              }
           ],
           "name":"removeCampaignAdmin",
           "outputs":[
              
           ],
           "stateMutability":"nonpayable",
           "type":"function"
        },
        {
           "inputs":[
              
           ],
           "name":"viewCampaigns",
           "outputs":[
              {
                 "components":[
                    {
                       "internalType":"uint256",
                       "name":"campaign_id",
                       "type":"uint256"
                    },
                    {
                       "internalType":"string",
                       "name":"title",
                       "type":"string"
                    },
                    {
                       "internalType":"string",
                       "name":"description",
                       "type":"string"
                    },
                    {
                       "internalType":"address",
                       "name":"campaignAddress",
                       "type":"address"
                    },
                    {
                       "internalType":"uint256",
                       "name":"targetAmount",
                       "type":"uint256"
                    },
                    {
                       "internalType":"uint256",
                       "name":"raisedAmount",
                       "type":"uint256"
                    },
                    {
                       "internalType":"uint256",
                       "name":"balance",
                       "type":"uint256"
                    },
                    {
                       "internalType":"uint256",
                       "name":"deadline",
                       "type":"uint256"
                    },
                    {
                       "internalType":"bool",
                       "name":"isCompleted",
                       "type":"bool"
                    },
                    {
                       "internalType":"bool",
                       "name":"isCancelled",
                       "type":"bool"
                    }
                 ],
                 "internalType":"struct CharityDonationStorage.Campaign[]",
                 "name":"",
                 "type":"tuple[]"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              
           ],
           "name":"viewDonations",
           "outputs":[
              {
                 "components":[
                    {
                       "internalType":"address",
                       "name":"campaignAddress",
                       "type":"address"
                    },
                    {
                       "internalType":"uint256",
                       "name":"campaignId",
                       "type":"uint256"
                    },
                    {
                       "internalType":"string",
                       "name":"title",
                       "type":"string"
                    },
                    {
                       "internalType":"uint256",
                       "name":"amount",
                       "type":"uint256"
                    }
                 ],
                 "internalType":"struct CharityDonationStorage.Donation[]",
                 "name":"",
                 "type":"tuple[]"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"_campaignAddress",
                 "type":"address"
              }
           ],
           "name":"viewWithdrawals",
           "outputs":[
              {
                 "components":[
                    {
                       "internalType":"uint256",
                       "name":"campaignId",
                       "type":"uint256"
                    },
                    {
                       "internalType":"string",
                       "name":"title",
                       "type":"string"
                    },
                    {
                       "internalType":"uint256",
                       "name":"amount",
                       "type":"uint256"
                    },
                    {
                       "internalType":"address",
                       "name":"by",
                       "type":"address"
                    },
                    {
                       "internalType":"address",
                       "name":"to",
                       "type":"address"
                    }
                 ],
                 "internalType":"struct CharityDonationStorage.Withdrawals[]",
                 "name":"withdrwals",
                 "type":"tuple[]"
              },
              {
                 "internalType":"address[]",
                 "name":"admins",
                 "type":"address[]"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"uint256",
                 "name":"_campaignId",
                 "type":"uint256"
              },
              {
                 "internalType":"address",
                 "name":"_campaignAddress",
                 "type":"address"
              },
              {
                 "internalType":"uint256",
                 "name":"_amount",
                 "type":"uint256"
              },
              {
                 "internalType":"address payable",
                 "name":"_to",
                 "type":"address"
              }
           ],
           "name":"withdrawFunds",
           "outputs":[
              
           ],
           "stateMutability":"nonpayable",
           "type":"function"
        },
        {
           "inputs":[
              {
                 "internalType":"address",
                 "name":"",
                 "type":"address"
              },
              {
                 "internalType":"uint256",
                 "name":"",
                 "type":"uint256"
              }
           ],
           "name":"withdrawals",
           "outputs":[
              {
                 "internalType":"uint256",
                 "name":"campaignId",
                 "type":"uint256"
              },
              {
                 "internalType":"string",
                 "name":"title",
                 "type":"string"
              },
              {
                 "internalType":"uint256",
                 "name":"amount",
                 "type":"uint256"
              },
              {
                 "internalType":"address",
                 "name":"by",
                 "type":"address"
              },
              {
                 "internalType":"address",
                 "name":"to",
                 "type":"address"
              }
           ],
           "stateMutability":"view",
           "type":"function"
        }
]
